name: SonarCloud Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install app and sonar dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-sonarqube.txt

      # 👇 This ensures Python can find your 'app' package during pytest
      - name: Add repo root to PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Run tests with coverage
        run: |
          pytest tests --cov=app --cov-report=xml

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=your_org_name
            -Dsonar.projectKey=your_org_name_your_repo
            -Dsonar.python.coverage.reportPaths=coverage.xml
